# Operating Systems Project 1
# CSC1021/simpleshell
# Name: Max Chan
# Student ID: 29134
# I acknowledgethe DCU Academic Integrity Policy

simpleshell: simpleshell.c utility.c simpleshell.h
	gcc -Wall simpleshell.c utility.c -o simpleshell